name: game403 # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A tiny game # 79 char long summary
description: |
  game403 teaches about rewards.


grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64

parts:
  alsa-lib:
    plugin: autotools
    source: ftp://ftp.alsa-project.org/pub/lib/alsa-lib-1.1.5.tar.bz2
    configflags:
      - --prefix=/usr
      - --sysconfdir=/etc
      - --libexec=/usr/lib
      - --libdir=/usr/lib
      - --localstatedir=/var
      - --with-configdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa
      - --with-plugindir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/alsa-lib
      - --disable-static
    stage:
      - usr/include
      - usr/lib
    prime:
      - -usr/bin
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/share/alsa/alsa.conf
      - -usr/share/alsa/pcm
      - -usr/share/alsa/topology/broadwell

  my-part:
    # See 'snapcraft plugins'
    plugin: go
    source: .
    build-snaps:
      - go
    build-packages:
      - build-essential
      - gcc
      - libgl1-mesa-dev
      - xorg-dev
      - libc6-dev
    after:
      - alsa-lib
    override-build: |
      set -xe
      go mod download
      go build -o $SNAPCRAFT_PART_INSTALL/bin/game403 ./windows


apps: 
  game403:
    command: bin/game403
    extensions: [gnome]
    environment:
      ALSA_CONFIG_PATH: /snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa
    plugs:
      - alsa
      - audio-playback